import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  keyboardAvoidingWrapper: {
    display: "flex",
    flex: 1,
    backgroundColor: "transparent",
  },
  mainContainer: {
    flex: 1,
    paddingTop: 20,
    backgroundColor: "white",
  },
  pickerArea: {
    flex: 1,
    alignContent: "center",
    position: "relative",
    width: "100%",
    height: "100%",
  },
  inputContainer: {
    flex: 1,
    marginVertical: 5,
  },
  label: {
    color: "black",
    marginBottom: 2,
    fontSize: 16,
  },
  publishInput: {
    width: "70%",
    backgroundColor: "white",
    borderColor: "#9FCEB4",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 15,
    height: 40,
    padding: 10,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  input: {
    width: "70%",
    backgroundColor: "white",
    borderColor: "#D9534F",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 15,
    height: 40,
    padding: 10,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  inputIcon: {
    alignItems: "center",
    justifyContent: "center",
    height: 38,
    width: 38,
  },
  inputText: {
    flex: 1,
    backgroundColor: "transparent",
    fontSize: 14,
    color: "black",
    height: 50,
    paddingVertical: 4,
  },
  loginHeader: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: "10%",
  },
  loginTitle: {
    fontSize: 40,
    color: "black",
  },
  loginForm: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loginFormTitle: {
    color: "black",
    fontSize: 16,
  },
  loginDivider: {
    height: 20,
    width: 200,
  },
  loginForgottenPassword: {
    width: 200,
    paddingTop: 4,
  },
  loginForgottenPasswordLink: {
    textAlign: "center",
    color: "grey",
    fontSize: 16,
    marginTop: 10,
  },
  loginButton: {
    width: 200,
    borderRadius: 25,
    padding: 3,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    backgroundColor: "#9FCEB4",
    borderColor: "#9FCEB4",
  },
  loginText: {
    fontSize: 18,
    color: "black",
  },
  loginScreenRegisterButton: {
    width: 200,
    borderRadius: 25,
    padding: 3,
    backgroundColor: "transparent",
    borderColor: "#D9534F",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    borderWidth: 1,
    borderStyle: "solid",
  },
  loginScreenRegisterText: {
    fontSize: 18,
    color: "#D9534F",
  },
  registerTitle: {
    fontSize: 24,
    color: "black",
    justifyContent: "center",
    textAlign: "center",
    padding: "5%",
  },
  registerForm: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  registerButton: {
    borderRadius: 25,
    paddingHorizontal: 45,
    paddingVertical: 7,
    backgroundColor: "#9FCEB4",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 90,
    borderWidth: 1,
    borderColor: "#9FCEB4",
    borderStyle: "solid",
  },
  registerText: {
    fontSize: 18,
  },
  registerHeader: {
    fontSize: 20,
    padding: 20,
  },
  searchContainer: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 0,
    position: "relative",
  },
  searchInput: {
    flex: 1,
    height: 40,
    paddingRight: 20,
    textAlign: "center",
    justifyContent: "center",
    fontSize: 20,
    marginTop: 4,
  },
  DateTimePicker: {
    // marginLeft: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  searchImage: {
    width: "100%",
    height: "50%",
    resizeMode: "cover",
  },
  searchInputGroup: {
    position: "absolute",
    top: "50%",
    width: "70%",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#d9534f",
    borderRadius: 10,
    backgroundColor: "white",
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "80%",
  },
  searchPersonIcon: {
    alignItems: "center",
    justifyContent: "center",
  },
  searchPersonInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "90%",
  },
  separatorLine: {
    height: 1,
    width: "80%",
    backgroundColor: "grey",
  },
  separatorLineOptions: {
    height: 1,
    width: "80%",
    backgroundColor: "grey",
    margin: 40,
  },
  iconStyle: {
    margin: 0,
  },
  textTilte: {
    margin: 25,
    fontSize: 25,
  },
  registerButtonPressed: {
    backgroundColor: "#d9534f",
  },
  personPicker: {
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  personPickerContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  pickerModal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalOption: {
    backgroundColor: "white",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginVertical: 5,
  },
  modalOptionText: {
    fontSize: 18,
    alignItems: "center",
  },
  verticalSeparatorLine: {
    height: "80%",
    width: 1,
    backgroundColor: "grey",
    marginLeft: 27,
  },
  dateTimePersonRow: {
    flexDirection: "row",
    marginLeft: 8,
  },
  modalOptionTextValue: {
    fontSize: 18,
    paddingLeft: 3,
  },
  styleLogo: {
    width: 100,
    height: 80,
    resizeMode: "contain",
    alignSelf: "center",
    marginTop: 40,
  },
  logOut: {
    color: "red",
    display: "flex",
    justifyContent: "center",
  },
  textXl: {
    fontSize: 20,
    fontWeight: "500",
    color: "#292524",
  },
  textLg: {
    fontSize: 15,
    color: "#292524",
    marginBottom: 10,
    textAlign: "center",
  },
  nbPassengerRemove: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  nbPassengerAdd: {
    flexDirection: "row",
    alignItems: "center",
  },
  passengersText: {
    marginHorizontal: 20,
    fontSize: 45,
  },
  titlePassengerText: {
    fontSize: 50,
  },
  addStartEnd: {
    alignItems: "center",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  TextInputAdd: {
    fontSize: 25,
    margin: 20,
  },
  bottomRightIcon: {
    position: "absolute",
    bottom: 15,
    right: 20,
    color: "#9FCEB4",
    fontSize: 34,
  },
  bottomLeftIcon: {
    position: "absolute",
    top: 15,
    left: 20,
    color: "#9FCEB4",
    fontSize: 34,
  },
  timerBorder: {
    fontSize: 50,
    backgroundColor: "white",
    borderColor: "#9FCEB4",
    borderStyle: "solid",
    borderWidth: 3,
    borderRadius: 55,
    padding: 15,
  },
  timerText: {
    position: "absolute",
    top: "15%",
    textAlign: "center",
    alignItems: "center",
    fontSize: 27,
  },
  passengerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 300,
    marginBottom: 20,
  },
  switchContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 10,
  },
  PickerStyle: {
    width: "100%",
    marginBottom: "5%",
  },
  textArea: {
    height: 150,
    width: 350,
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 15,
    padding: 10,
    fontSize: 16,
    textAlignVertical: "top",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  modalView: {
    margin: 20,
    backgroundColor: "#FFeead",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    marginBottom: 10,
    textAlign: "center",
    fontSize: 20,
  },
  textTilteCreate: {
    fontSize: 25,
    textAlign: "center",
    top: 30,
  },
  textTiltePassenger: {
    fontSize: 15,
    textAlign: "center",
    top: 90,
  },
});
